name       : tpm2-tools
version    : '5.5'
release    : 3
source     :
    - https://github.com/tpm2-software/tpm2-tools/releases/download/5.5/tpm2-tools-5.5.tar.gz : 1fdb49c730537bfdaed088884881a61e3bfd121e957ec0bdceeec0261236c123
license    : BSD-2-Clause
component  : security
summary    : Trusted Platform Module (TPM2.0) tools
description: |
    Trusted Platform Module (TPM2.0) tools based on tpm2-tss
builddeps  :
    - pkgconfig(efivar)
    - pkgconfig(tss2-esys)
    - pandoc
setup      : |
    %configure --with-efivar
build      : |
    %make
install    : |
    %make_install
# Requires tpm2-abrmd
# check      : |
#    %make check
